apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rails-mysql
  labels:
    app: hello-docker-rails
spec:
  selector:
    matchLabels:
      app: hello-docker-rails
      tier: mysql
  template:
    metadata:
      labels:
        app: hello-docker-rails
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_USER
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim