apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: hello-docker-rails
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi