apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    app: hello-docker-rails
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: hello-docker-rails
    tier: backend